
name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.8.1
        with:
          node-version: 18.x

      - name: install modules
        run: yarn install --production

      - name: run test
        run: |
          yarn add jest
          sudo yarn test

      - name: Docker Login
       
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
        

      - name: Build and push to Dockerhub
        run: |
          docker build -t gdsc .
          docker tag gdsc:latest $/gdsc:latest
          docker push synoti21/gdsc:latest
